name: Mirror repo to S3
on:
  push:
    branches:
      - master
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: AKIAXECJTNR7JKJJ4YPJ
          SECRET_ACCESS_KEY: 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
        with:
          args: --overwrite --remove
